name: badua_coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build
        run: mvn clean verify -P ba-dua-coverage
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: badua-report
          path: bookkeeper-server/target/badua.xml
          if-no-files-found: error
